name: dung.men
on: push
jobs:
  deploy:
    runs-on: latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths